name: connectivity
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
